### ISSUE TITLE
debug:start-page changes to about:blank

### ISSUE THREAD

**Issue by PonchoPowers** [cefsharp/Questions-and-Support#68] opened 2020-11-21 08:34 UTC
I am wondering if it is possible to handle when an invalid URL changes to about:blank?

If I enter test:123 into the URL, about:blank loads.

Ideally, I'd like to detect any invalid URL rather than have it just change to about:blank so that I can determine what should happen.

Is this possible already and if not can this be added?

**Comment by amaitland** [comment] 2020-11-23 00:20
> I am wondering if it is possible to handle when an invalid URL changes to about:blank?

How do you reproduce this exactly?
What version are you using?

Using the [MinimaExample](https://github.com/cefsharp/CefSharp.MinimalExample) and adding a [LoadError](http://cefsharp.github.io/api/85.3.x/html/E_CefSharp_IWebBrowser_LoadError.htm) event handler I see the following:

- Loading `debug:start-page` has an `ErrorCode` of  `CefErrorCode.UnknownUrlScheme`
- Loading `test:123`  has an  `ErrorCode` of `CefErrorCode.UnsafePort` 

It's possible this behaviour will change depending on the `CEF/Chromium` version used

> Ideally, I'd like to detect any invalid URL rather than have it just change to about:blank so that I can determine what should happen.

I don't recall seeing the behaviour you are describing before. Nor can I reproduce it now. This is part of the reason I'd ask you'd avoid using the `Feature Request` template. In future please open a question in this repository instead and fill out the [Question Template](https://github.com/cefsharp/Questions-and-Support/blob/master/.github/ISSUE_TEMPLATE/question-template.md) which saves me having to ask everyone the same questions. If code changes are required to the main project then the issue can simply be transferred across.

> Is this possible already and if not can this be added?

`CefSharp` doesn't performing any sort of validation it simply passes the `Url` as is to `CEF/Chromium`, if `LoadError` isn't being called in your scenario then if you need the default behaviour changed you'll need to discuss that on https://magpcss.org/ceforum/index.php

I don't believe this is anything `CefSharp` can control directly.  Regardless I'd always recommend performing some sort of validation before calling `Load` or passing to the `ChromiumWebBrowser` constructor.

**Comment by PonchoPowers** [comment] 2020-11-23 07:43
I started with the minimal example as you mentioned using the winforms project.

I didn't add a load error.

I simply type something like test:foobar into the URL, the address bar stays the same but the ChromiumWebBrowser.Address property contains about:blank.

I'm creating the instance using `new ChromiumWebBrowser("about:blank") so I presume this is where the about:blank is coming from but I can load another page and then in the URL type something random again and still the same thing happens.

**Comment by PonchoPowers** [comment] 2020-11-23 08:01
Figured it out, the FrameLoadEnd event is being raised, but the browser.Address is not updating, and even more confusing is that the winform address bar shows a different URL. If the page didn't load due to an error, why is FrameLoadEnd being raised?

```csharp
browser.FrameLoadEnd += OnBrowserFrameLoadEnd;

private void OnBrowserFrameLoadEnd(object sender, FrameLoadEndEventArgs e)
{
    Console.WriteLine(browser.Address);
}
```

Is this expected or a bug?

**Comment by amaitland** [comment] 2020-11-23 09:32
> I simply type something like test:foobar into the URL, the address bar stays the same but the ChromiumWebBrowser.Address property contains about:blank.

What are the steps to reproduce this exactly? 

> Figured it out, the FrameLoadEnd event is being raised, but the browser.Address is not updating, and even more confusing is that the winform address bar shows a different URL. If the page didn't load due to an error, why is FrameLoadEnd being raised?

You need to implement `LoadError` and display an error page, `CEF` doesn't provide a default implementation. 

> Is this expected or a bug?

I guess technically it's a bug in `CEF`. Historically it was called regardless of error, the documentation changed, the behaviour did not, at least not in all cases. https://magpcss.org/ceforum/index.php is the place to discuss improvements.

Old doc https://github.com/chromiumembedded/cef/blob/2987/include/cef_load_handler.h#L86
New doc https://github.com/chromiumembedded/cef/blob/4240/include/cef_load_handler.h#L97

**Closed as completed** 2020-12-14 12:13 UTC
Labels: question
